openapi: 3.0.3
info:
  title: TEP REST API
  description: |-
    REST API specification for integration of TEP components

    Some useful links:
    - [The repository](https://github.com/hi-tep/tep-rest-api)
  termsOfService: http://swagger.io/terms/
  contact:
    email: p.t.j.m.vossen@vu.nl
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: leolani
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: Operations about user
paths:
  /gaze:
    post:
      summary: Submit bounding box in an image
      operationId: submitBoundingBox
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
                  description: IRI of the image where the bounding box is located.
                  example: "http://example.com/image.jpg"
                entity:
                  type: string
                  description: IRI of the entity contained in the bounding box
                  example: "http://example.com/ontology/king/tubby"
                boundingBox:
                  $ref: '#/components/schemas/BoundingBox'
      responses:
        '200':
          description: Successfully submitted bounding box
        '400':
          description: Invalid bounding box input

components:
  schemas:
    BoundingBox:
      type: object
      required:
        - bottomLeft
        - topRight
      properties:
        bottomLeft:
          $ref: '#/components/schemas/Coordinate'
        topRight:
          $ref: '#/components/schemas/Coordinate'
    Coordinate:
      type: object
      description: Pixel-Coordinates of a point in the image
      required:
        - x
        - y
      properties:
        x:
          type: number
          example: 1.0
        y:
          type: number
          example: 2.0
